-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. USERS & PROFILES (RBAC)
-- ==========================================

-- Create a table for public profiles (linked to auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  role TEXT CHECK (role IN ('admin', 'teacher', 'student', 'parent')) NOT NULL,
  avatar_url TEXT,
  phone_number TEXT,
  preferred_stream TEXT, -- e.g., 'JEE', 'NEET', 'Board Exams'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Parent-Student Relationship
CREATE TABLE parent_student_link (
  parent_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (parent_id, student_id)
);

-- ==========================================
-- 2. MANAGEMENT MODULES
-- ==========================================

-- Batches
CREATE TABLE batches (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL, -- e.g., "Organic Chem - Batch A"
  teacher_id UUID REFERENCES profiles(id),
  schedule JSONB, -- e.g., {"Mon": "10:00", "Wed": "10:00"}
  stream TEXT, -- e.g., "Class 12 - Boards"
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enrollments (Student-Batch Many-to-Many)
CREATE TABLE enrollments (
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  batch_id UUID REFERENCES batches(id) ON DELETE CASCADE,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (student_id, batch_id)
);

-- Attendance
CREATE TABLE attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  batch_id UUID REFERENCES batches(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT CHECK (status IN ('present', 'absent', 'late')) NOT NULL,
  scan_time TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Fee Payments
CREATE TABLE fee_payments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  amount_due DECIMAL(10, 2) NOT NULL,
  amount_paid DECIMAL(10, 2) DEFAULT 0,
  due_date DATE NOT NULL,
  status TEXT CHECK (status IN ('paid', 'pending', 'overdue')) DEFAULT 'pending',
  invoice_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. CONTENT & LMS
-- ==========================================

-- Topics
CREATE TABLE topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, -- e.g., "Thermodynamics"
  category TEXT CHECK (category IN ('Physical', 'Organic', 'Inorganic')) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Resources
CREATE TABLE resources (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL,
  type TEXT CHECK (type IN ('video', 'pdf', 'simulation_link')) NOT NULL,
  url TEXT NOT NULL,
  topic_id BIGINT REFERENCES topics(id) ON DELETE SET NULL,
  access_level TEXT CHECK (access_level IN ('free', 'premium')) DEFAULT 'free',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Assignments
CREATE TABLE assignments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  batch_id UUID REFERENCES batches(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  due_date TIMESTAMP WITH TIME ZONE,
  max_marks INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Submissions
CREATE TABLE submissions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  assignment_id UUID REFERENCES assignments(id) ON DELETE CASCADE,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  file_url TEXT,
  teacher_remarks TEXT,
  marks_obtained INTEGER,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(assignment_id, student_id)
);

-- ==========================================
-- 4. GAMIFICATION
-- ==========================================

-- Daily Challenges
CREATE TABLE daily_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL DEFAULT CURRENT_DATE,
  question_json JSONB NOT NULL, -- {"q": "...", "options": [...], "ans": ...}
  points_reward INTEGER DEFAULT 10
);

-- Student Stats
CREATE TABLE student_stats (
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE PRIMARY KEY,
  total_points INTEGER DEFAULT 0,
  current_streak INTEGER DEFAULT 0,
  badges TEXT[] DEFAULT '{}',
  last_activity_date DATE
);

-- ==========================================
-- 5. LOGIC & TRIGGERS
-- ==========================================

-- Function to handle new user signup -> create profile and stats
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', COALESCE(new.raw_user_meta_data->>'role', 'student'));
  
  -- Initialize stats for students
  IF (new.raw_user_meta_data->>'role' = 'student') THEN
    INSERT INTO public.student_stats (student_id) VALUES (new.id);
  END IF;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- Function to check premium access based on fee status
CREATE OR REPLACE FUNCTION check_premium_access(user_uuid UUID)
RETURNS BOOLEAN AS $$
DECLARE
  has_overdue BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM fee_payments 
    WHERE student_id = user_uuid AND status = 'overdue'
  ) INTO has_overdue;
  
  RETURN NOT has_overdue;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 6. SECURITY (RLS)
-- ==========================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE fee_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_stats ENABLE ROW LEVEL SECURITY;

-- Profiles: Public read, User edit own
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Attendance: partial policy (Admins all, Students view own)
CREATE POLICY "Admins view all attendance" ON attendance FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);
CREATE POLICY "Students view own attendance" ON attendance FOR SELECT USING (student_id = auth.uid());

-- Fees: Admins all, Students view own
CREATE POLICY "Admins view all fees" ON fee_payments FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);
CREATE POLICY "Students view own fees" ON fee_payments FOR SELECT USING (student_id = auth.uid());


-- Function to check if the current user has overdue fees
CREATE OR REPLACE FUNCTION public.has_overdue_fees()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.fee_payments
    WHERE student_id = auth.uid() -- Matches the currently logged-in user
    AND status = 'overdue'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Resources: Logic-based access (No Pay, No Notes)
CREATE POLICY "Enforce Premium Content Access" ON resources FOR SELECT USING (
  -- Condition 1: Everyone can see 'free' content
  access_level = 'free'
  OR
  -- Condition 2: To see 'premium', you must NOT have overdue fees
  (
    access_level = 'premium' 
    AND 
    NOT public.has_overdue_fees()
  )
);
